name:                sdma-assembler
version:             0.1.0.0
github:              "bsh-git/SDMA_assembler"
license:             BSD3
author:              "Hiroyuki Bessho"
maintainer:          "bessho@genetec.co.jp"
copyright:           "2020 Genetec corp."

extra-source-files:
- ../../README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/bsh-git/SDMA_assembler#readme>

dependencies:
- base >= 4.7 && < 5
- text
- megaparsec >= 8.0
- utility-ht
- containers
- parser-combinators
- list-singleton

library:
  source-dirs: src

executables:
  sdmaasm-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sdma-assembler

tests:
  sdmaasm-test:
    main:                test.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sdma-assembler
    - HUnit
